import { ACTIVE_EVENT_PACK, MILESTONES, MINION_TYPES, PHASES } from "./config";
import type { EventState } from "./types";

export const INITIAL_EVENT_STATE: EventState = {
  version: 4,
  updatedAt: "2026-08-10T20:00:00.000Z",
  event: {
    id: "00000000-0000-4000-8000-000000000101",
    slug: ACTIVE_EVENT_PACK.events.find((event) => event.variant === "test")?.slug ?? ACTIVE_EVENT_PACK.events[0].slug,
    name: `${ACTIVE_EVENT_PACK.name} – Test`,
    description: `Lokaler Testlauf für ${ACTIVE_EVENT_PACK.name}.`,
    status: "testing",
    active: true,
    isTest: true,
    packKey: ACTIVE_EVENT_PACK.key,
    packVersion: ACTIVE_EVENT_PACK.version,
  },
  boss: {
    id: "00000000-0000-4000-8000-000000000201",
    name: ACTIVE_EVENT_PACK.boss.name,
    maxHp: ACTIVE_EVENT_PACK.boss.defaultMaxHp,
    currentHp: ACTIVE_EVENT_PACK.boss.defaultMaxHp,
    phase: PHASES[0].id,
    phaseName: PHASES[0].name,
  },
  phases: PHASES.map((phase, index) => ({
    id: phase.id,
    name: phase.name,
    minPercent: phase.minPercent,
    maxPercent: phase.maxPercent,
    color: phase.color,
    sortOrder: index + 1,
    metadata: { intensity: phase.intensity, spawnWindowMinutes: phase.spawnWindowMinutes },
  })),
  minionDefinitions: Object.values(MINION_TYPES).map((definition) => ({
    id: `definition-${definition.id}`,
    key: definition.id,
    name: definition.name,
    icon: definition.icon,
    gameMode: definition.gameMode,
    phaseMinimum: definition.phaseMin,
    damageClass: definition.damageClass,
    presentation: definition.presentation,
    enabled: true,
  })),
  settings: {
    eventPaused: false,
    damageEnabled: true,
    minionsEnabled: true,
    globalDamageMultiplier: 1,
    passiveDamageMultiplier: 1,
    activeDamageMultiplier: 1,
    passiveTickSeconds: 120,
    twitchTrackingEnabled: true,
    passiveDamageEnabled: true,
    passiveDamageMode: "test",
    passiveBaseDamage: 10,
    passiveCurveExponent: 0.72,
    passiveSoftCap: 50,
    passiveMinDamage: 0,
    passiveMaxDamage: 5_000,
    passiveUnderdogFactor: 0.15,
    passiveConfigurationVersion: 1,
  },
  stats: {
    globalDamage: 0,
    minionsDefeated: 0,
    minionsEscaped: 0,
    communities: 2,
    uniqueParticipants: 0,
  },
  streamers: [
    { id: "streamer-alpha", slug: "channel-alpha", displayName: "Channel Alpha", communityName: "Alpha Community", twitchLogin: "channel_alpha", twitchUserId: "mock-1001", twitchUrl: "https://twitch.tv/channel_alpha", avatarUrl: null, enabled: true, trackingEnabled: true, gameplayEnabled: true, publicVisible: true, includeInCalibration: true, damage: 0, minionsDefeated: 0, live: true, liveSince: "2026-08-10T19:00:00.000Z", currentStreamId: "mock-stream-1001", currentViewerCount: 23, lastTwitchSyncAt: "2026-08-10T20:00:00.000Z", lastSeenLiveAt: "2026-08-10T20:00:00.000Z", latestSession: { id: "mock-session-1001", streamId: "mock-stream-1001", startedAt: "2026-08-10T19:00:00.000Z", endedAt: null, status: "live", averageViewers: 20, peakViewers: 27, latestViewers: 23, sampleCount: 30, durationSeconds: 3_600 }, sortOrder: 1 },
    { id: "streamer-beta", slug: "channel-beta", displayName: "Channel Beta", communityName: "Beta Community", twitchLogin: "channel_beta", twitchUserId: "mock-1002", twitchUrl: "https://twitch.tv/channel_beta", avatarUrl: null, enabled: true, trackingEnabled: true, gameplayEnabled: true, publicVisible: true, includeInCalibration: true, damage: 0, minionsDefeated: 0, live: false, liveSince: null, currentStreamId: null, currentViewerCount: 0, lastTwitchSyncAt: "2026-08-10T20:00:00.000Z", lastSeenLiveAt: null, latestSession: null, sortOrder: 2 },
  ],
  minions: [],
  milestones: MILESTONES.map((milestone, index) => ({
    id: `milestone-${milestone.percent}`,
    label: milestone.label,
    percent: milestone.percent,
    description: milestone.description,
    reachedAt: milestone.percent >= 75 ? "2026-08-10T19:45:00.000Z" : null,
    sortOrder: index + 1,
  })),
  twitch: {
    health: {
      status: "healthy",
      reason: "Mock-Twitch-Sync erfolgreich; im Supabase-Modus werden echte Twitch-Daten verwendet.",
      webhookConfigured: true,
      lastSyncAt: "2026-08-10T20:00:00.000Z",
      lastSuccessAt: "2026-08-10T20:00:00.000Z",
      lastErrorAt: null,
      lastError: null,
      lastWebhookAt: "2026-08-10T19:58:42.000Z",
      lastInvalidSignatureAt: null,
      lastSubscriptionSyncAt: "2026-08-10T19:55:00.000Z",
    },
    subscriptions: { online: 4, offline: 4, raid: 8, pending: 0, revokedOrError: 0 },
    recentRaids: [],
    passiveDamagePreview: null,
  },
  passiveDamage: {
    id: null, streamerId: null, bucketStartedAt: null, mode: "test", viewerEstimate: null,
    sampleCount: 0, configuredDamage: 0, appliedDamage: 0, status: "none", skipReason: null,
    configurationVersion: 1, processedAt: null,
  },
  jobs: [],
  calibration: {
    streamers: [], includedStreamers: 0, totalSamples: 0, projectedPassiveDamage: 0,
    projectedPassiveDamagePerHour: 0, maxConcurrentStreamers: 0,
    minionsSpawned: 0, minionsDefeated: 0, minionsFailed: 0,
  },
  log: [
    { id: "initial-1", timestamp: "2026-08-10T20:00:00.000Z", type: "system", message: "PXB Event Engine development fixture loaded", actor: "local-development" },
  ],
};
