// Browser-safe project identifiers are embedded once by the event operator before creating the Share Link.
const SUPABASE_URL = "https://YOUR_PROJECT.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_REPLACE_ME";
const WIDGET_EVENT_SLUG = "halloween-2026";
const FALLBACK_REFRESH_MS = 5_000;
const DEBUG_IDENTITY = false;
const DEV_STREAMER_OVERRIDE = "";
const DEV_EVENT_OVERRIDE = "";
const MINION_ARTWORK_BASE = "https://psychoxbounty96.github.io/Kuerbiskoenig-Event/assets/minions";
const MINION_ARTWORK_FOLDERS = Object.freeze({ghost:"ghost",zombie_horde:"zombie",spider_queen:"spider",witch:"witch",bat_swarm:"bats",reaper:"reaper",kings_herald:"herald"});

const IDENTITY_STATUSES = new Set(["resolved","not_registered","disabled","event_unavailable","error"]);
const OPEN_MINION_STATUSES = new Set(["intro","active","success","failure","curse"]);
let identity = createIdentity("loading");
let channelUsername = "";
let lastSafeState = null;
let refreshTimer = null;
let clockTimer = null;
let realtimeChannel = null;
let supabaseClient = null;

function normalizeTwitchLogin(value){return typeof value==="string"?value.trim().toLowerCase():""}
function normalizeEventSlug(value){const normalized=typeof value==="string"?value.trim().toLowerCase():"";return /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(normalized)?normalized:""}
function configuredEventSlug(){return DEBUG_IDENTITY&&normalizeEventSlug(DEV_EVENT_OVERRIDE)?normalizeEventSlug(DEV_EVENT_OVERRIDE):WIDGET_EVENT_SLUG}
function createIdentity(status,payload={}){return{status,channelUsername:payload.channel_username||null,eventId:payload.event_id||null,eventSlug:payload.event_slug||configuredEventSlug(),eventStatus:payload.event_status||null,streamerId:payload.streamer_id||null,streamerSlug:payload.streamer_slug||null,streamerDisplayName:payload.streamer_display_name||null}}
function number(value){const parsed=Number(value);return Number.isFinite(parsed)?Math.max(0,parsed):0}
function milliseconds(value){const parsed=Date.parse(value||"");return Number.isFinite(parsed)?parsed:0}
function setIdentity(next){identity=next;document.getElementById("pumpkin-widget").dataset.identityStatus=next.status}
function hideOverlay(status){setIdentity({...identity,status});document.getElementById("pumpkin-widget").hidden=true;document.getElementById("identity-card").hidden=true;document.getElementById("boss-card").hidden=true;document.getElementById("minion-card").hidden=true;document.getElementById("curse-layer").hidden=true}
function showIdentityMessage(title,detail,debugOnly=false){if(debugOnly&&!DEBUG_IDENTITY){hideOverlay(identity.status);return}const widget=document.getElementById("pumpkin-widget");widget.hidden=false;document.getElementById("boss-card").hidden=true;document.getElementById("minion-card").hidden=true;document.getElementById("identity-card").hidden=false;document.getElementById("identity-title").textContent=title;document.getElementById("identity-detail").textContent=detail}
async function rpc(name,body){if(SUPABASE_URL.includes("YOUR_PROJECT")||SUPABASE_PUBLISHABLE_KEY.includes("REPLACE_ME"))throw new Error("widget_backend_not_configured");const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:"POST",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${SUPABASE_PUBLISHABLE_KEY}`,"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok)throw new Error(`widget_rpc_${name}_failed`);return response.json()}
async function resolveIdentity(){const normalized=normalizeTwitchLogin(channelUsername);if(!normalized)return createIdentity("error",{event_slug:configuredEventSlug()});const payload=await rpc("resolve_stream_elements_identity",{p_event_slug:configuredEventSlug(),p_twitch_login:normalized});return createIdentity(IDENTITY_STATUSES.has(payload?.status)?payload.status:"error",payload||{})}
function renderPreLaunch(){showIdentityMessage("Overlay erfolgreich verbunden",`${identity.streamerDisplayName||identity.channelUsername} · Event startet bald`)}
function currentMinion(state){return(state?.minions||[]).find(item=>item.streamer_id===identity.streamerId&&OPEN_MINION_STATUSES.has(item.status))||null}
function element(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node}
function minionArtwork(minion){const folder=MINION_ARTWORK_FOLDERS[minion.key];if(!folder)return element("span","minion-icon",minion.icon||"👻");const frame=element("span","minion-artwork");const image=element("img");image.src=`${MINION_ARTWORK_BASE}/${folder}/placeholder.jpg`;image.alt="";image.setAttribute("aria-hidden","true");frame.append(image);return frame}
function renderVisual(minion,observing){const config=minion.runtime_config||{};const box=element("div","minion-visual");if(minion.key==="zombie_horde"){for(const direction of["links","mitte","rechts"]){const item=element("span",observing&&config.visual_target===direction?"is-target":"",direction==="links"?"←":direction==="rechts"?"→":"↑");item.append(element("em","",direction));box.append(item)}return box}if(minion.key==="spider_queen"){for(const option of config.options||[]){const item=element("span",String(config.queen_index)===String(option)?"is-target":"","🕷️");item.append(element("b","",String(option)));box.append(item)}return box}if(minion.key==="bat_swarm"&&observing){for(let i=0;i<number(config.count);i+=1)box.append(element("span","","🦇"));return box}if(minion.key==="reaper"&&observing){for(const item of config.sequence||[])box.append(element("span","",String(item)));return box}if(minion.key==="witch"||minion.key==="reaper"){const question=element("div","minion-question");if(config.question)question.append(element("strong","",String(config.question)));for(const key of["a","b","c"])question.append(element("span","",`${key.toUpperCase()} – ${String(config.option_labels?.[key]||"")}`));return question}return null}
function renderCurse(minion){const layer=document.getElementById("curse-layer");if(minion?.status!=="curse"||!minion.failure_curse_key){layer.hidden=true;layer.className="curse-layer";return}layer.hidden=false;layer.className=`curse-layer curse-layer--${minion.failure_curse_key}`}
function renderMinion(minion){const card=document.getElementById("minion-card");if(!minion){card.hidden=true;card.replaceChildren();renderCurse(null);return}renderCurse(minion);card.hidden=false;card.className=`minion-card minion-card--${minion.status}`;const icon=minionArtwork(minion);const copy=element("div","minion-copy");const timer=element("time","");if(minion.status==="intro"){copy.append(element("small","",`MINION-ALARM · ${identity.streamerDisplayName}`),element("h2","",minion.intro_title||minion.name));card.replaceChildren(icon,copy);return}if(minion.status==="active"){const now=Date.now();const observing=now<milliseconds(minion.accepts_answers_at);copy.append(element("small","",`${minion.game_mode} · ${minion.damage_class}`),element("h2","",observing?"Gut aufpassen …":minion.gameplay_title||minion.name));const visual=renderVisual(minion,observing);if(visual)copy.append(visual);if(!observing){copy.append(element("p","command",minion.instruction||"Schreibe !boss"),element("p","progress",`${number(minion.participant_count)} / ${number(minion.required_participants)} Teilnehmer`));const left=Math.max(0,Math.ceil((milliseconds(minion.expires_at)-now)/1000));timer.textContent=`${String(Math.floor(left/60)).padStart(2,"0")}:${String(left%60).padStart(2,"0")}`;card.replaceChildren(icon,copy,timer)}else card.replaceChildren(icon,copy);return}if(minion.status==="success"){copy.append(element("small","","MINION BESIEGT"),element("h2","",`${minion.name} besiegt!`),element("p","",`${number(minion.damage_awarded).toLocaleString("de-DE")} Boss-Schaden`));card.replaceChildren(icon,copy);return}if(minion.status==="failure"){copy.append(element("small","","MINION ENTKOMMEN"),element("h2","",`${minion.name} war zu stark`),element("p","",`Fluch: ${String(minion.failure_curse_key||"").replaceAll("_"," ")}`));card.replaceChildren(icon,copy);return}if(minion.status==="curse"){copy.append(element("small","","FLUCH AKTIV"),element("h2","",String(minion.failure_curse_key||"").replaceAll("_"," ")));card.replaceChildren(icon,copy);return}card.hidden=true}
function renderEvent(state){if(!identity.streamerId||state?.event?.id!==identity.eventId){hideOverlay("error");return}const status=state.event.status;const paused=status==="paused"||Boolean(state?.settings?.event_paused);if(status!=="active"&&!paused){hideOverlay("event_unavailable");return}const boss=state.boss||{};const maxHp=number(boss.max_hp);const currentHp=Math.min(maxHp,number(boss.current_hp));document.getElementById("boss-name").textContent=boss.name||"Kürbiskönig";document.getElementById("boss-hp").textContent=`${Math.floor(currentHp).toLocaleString("de-DE")} / ${Math.floor(maxHp).toLocaleString("de-DE")} HP`;document.getElementById("health-fill").style.width=`${maxHp?(currentHp/maxHp)*100:0}%`;const eventState=document.getElementById("event-state");eventState.hidden=!paused;eventState.textContent=paused?"Event pausiert · Fortsetzung erfolgt automatisch":"";document.getElementById("pumpkin-widget").hidden=false;document.getElementById("identity-card").hidden=true;document.getElementById("boss-card").hidden=false;renderMinion(paused?null:currentMinion(state))}
function setupRealtime(){if(!window.supabase?.createClient||!identity.eventId)return;realtimeChannel?.unsubscribe?.();supabaseClient=supabaseClient||window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false}});const refresh=()=>void refreshWidget(false);realtimeChannel=supabaseClient.channel(`se-widget:${identity.eventId}:${identity.streamerId}`).on("postgres_changes",{event:"*",schema:"public",table:"minion_events",filter:`event_id=eq.${identity.eventId}`},refresh).on("postgres_changes",{event:"UPDATE",schema:"public",table:"bosses",filter:`event_id=eq.${identity.eventId}`},refresh).on("postgres_changes",{event:"UPDATE",schema:"public",table:"events",filter:`id=eq.${identity.eventId}`},refresh).on("postgres_changes",{event:"UPDATE",schema:"public",table:"streamers",filter:`id=eq.${identity.streamerId}`},refresh).subscribe()}
async function refreshWidget(reconnectRealtime=false){try{const resolved=await resolveIdentity();const changed=resolved.eventId!==identity.eventId||resolved.streamerId!==identity.streamerId;setIdentity(resolved);if(resolved.status!=="resolved"){lastSafeState=null;if(resolved.status==="not_registered"||resolved.status==="disabled")showIdentityMessage("Dieser Kanal ist nicht freigeschaltet.","Bitte Eventorganisation kontaktieren.",true);else hideOverlay(resolved.status);return}if((changed||reconnectRealtime)&&!SUPABASE_URL.includes("YOUR_PROJECT"))setupRealtime();if(resolved.eventStatus==="draft"||resolved.eventStatus==="testing"){lastSafeState=null;renderPreLaunch();return}const state=await rpc("get_public_event_state",{p_event_slug:configuredEventSlug()});lastSafeState=state;renderEvent(state)}catch(error){console.warn("Kürbiskönig refresh failed; safe state retained.",error instanceof Error?error.message:"unknown");if(identity.status==="resolved"&&lastSafeState)renderEvent(lastSafeState);else hideOverlay("error")}}
function parseBossCommand(value){if(typeof value!=="string")return null;const tokens=value.trim().split(/\s+/).filter(Boolean);if(!tokens.length||tokens[0].toLowerCase()!=="!boss"||tokens.length>2)return null;return{answer:tokens[1]?.toLowerCase()||null}}
function extractChatAction(event){if(event?.detail?.listener!=="message")return null;const data=event?.detail?.event?.data||{};const userId=String(data.userId||data.user_id||data.tags?.["user-id"]||"").trim();const messageId=String(data.msgId||data.msg_id||data.tags?.id||`se-${userId}-${Date.now()}`).trim();const text=String(data.text||"");return userId&&text?{userId,messageId,text}:null}
async function handleStreamElementsChatMessage(event){if(identity.status!=="resolved"||!lastSafeState||lastSafeState.event?.status!=="active"||lastSafeState.settings?.event_paused)return;const minion=currentMinion(lastSafeState);if(!minion||minion.status!=="active"||Date.now()<milliseconds(minion.accepts_answers_at)||Date.now()>=milliseconds(minion.expires_at))return;const action=extractChatAction(event);if(!action||!parseBossCommand(action.text))return;const response=await fetch(`${SUPABASE_URL}/functions/v1/minion-action`,{method:"POST",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${SUPABASE_PUBLISHABLE_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({eventId:identity.eventId,streamerId:identity.streamerId,minionEventId:minion.id,participantId:action.userId,messageId:action.messageId,text:action.text})});if(response.ok)void refreshWidget(false)}
window.addEventListener("onWidgetLoad",obj=>{const automaticUsername=normalizeTwitchLogin(obj?.detail?.channel?.username);channelUsername=automaticUsername||(DEBUG_IDENTITY?normalizeTwitchLogin(DEV_STREAMER_OVERRIDE):"");if(!channelUsername){console.debug("Kürbiskönig: StreamElements channel.username fehlt.");hideOverlay("error");return}void refreshWidget(true);window.clearInterval(refreshTimer);refreshTimer=window.setInterval(()=>void refreshWidget(false),FALLBACK_REFRESH_MS);window.clearInterval(clockTimer);clockTimer=window.setInterval(()=>{if(lastSafeState&&identity.status==="resolved")renderEvent(lastSafeState)},250)});
window.addEventListener("onEventReceived",event=>{if(event.detail?.listener==="message")void handleStreamElementsChatMessage(event)});
